### ISSUE TITLE
errors with sab 3.7.2

### ISSUE THREAD

**Issue by halfagascan** [mdhiggins/sma-mod#12]
After having no processing, down mix audio and removing subtitles, troubleshooting, first issue visible in sab, something about no plex api configured, I have no need for plex, nothing in my system uses plex, deleted the docker image, repulled, now getting the below error.

From SAB webui:
2023-04-17 11:13:50 - SABPostProcess - INFO - SAB post processing started.
2023-04-17 11:13:50 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3
2023-04-17 11:13:50 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
2023-04-17 11:13:50 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
File "/usr/local/sma/SABPostProcess.py", line 33, in <module>
settings = ReadSettings()
File "/usr/local/sma/resources/readsettings.py", line 469, in __init__
self.readConfig(config)
File "/usr/local/sma/resources/readsettings.py", line 836, in readConfig
self.Plex['port'] = config.getint(section, "port")
File "/usr/local/sma/resources/readsettings.py", line 89, in getint
return super(SMAConfigParser, self).getint(section, option, vars=vars)
File "/usr/lib/python3.10/configparser.py", line 820, in getint
return self._get_conv(section, option, int, raw=raw, vars=vars,
File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
return self._get(section, conv, option, raw=raw, vars=vars,
File "/usr/lib/python3.10/configparser.py", line 805, in _get
return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: ''

From sma.log:
2023-04-17 10:12:23 - SABPostProcess - INFO - SAB post processing started.
2023-04-17 10:12:23 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3
2023-04-17 10:12:23 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
2023-04-17 10:12:23 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "/usr/local/sma/SABPostProcess.py", line 33, in <module>
    settings = ReadSettings()
  File "/usr/local/sma/resources/readsettings.py", line 469, in __init__
    self.readConfig(config)
  File "/usr/local/sma/resources/readsettings.py", line 836, in readConfig
    self.Plex['port'] = config.getint(section, "port")
  File "/usr/local/sma/resources/readsettings.py", line 89, in getint
    return super(SMAConfigParser, self).getint(section, option, vars=vars)
  File "/usr/lib/python3.10/configparser.py", line 820, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 805, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: ''
2023-04-17 10:20:27 - SABPostProcess - INFO - SAB post processing started.
2023-04-17 10:20:27 - SABPostProcess - ERROR - Not enough command line parameters specified. Is this being called from SAB?
2023-04-17 10:22:05 - SABPostProcess - INFO - SAB post processing started.
2023-04-17 10:22:05 - SABPostProcess - ERROR - Not enough command line parameters specified. Is this being called from SAB?
2023-04-17 11:13:50 - SABPostProcess - INFO - SAB post processing started.
2023-04-17 11:13:50 - resources.readsettings - INFO - /usr/local/sma/venv/bin/python3
2023-04-17 11:13:50 - resources.readsettings - INFO - Loading config file /usr/local/sma/config/autoProcess.ini.
2023-04-17 11:13:50 - SABPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "/usr/local/sma/SABPostProcess.py", line 33, in <module>
    settings = ReadSettings()
  File "/usr/local/sma/resources/readsettings.py", line 469, in __init__
    self.readConfig(config)
  File "/usr/local/sma/resources/readsettings.py", line 836, in readConfig
    self.Plex['port'] = config.getint(section, "port")
  File "/usr/local/sma/resources/readsettings.py", line 89, in getint
    return super(SMAConfigParser, self).getint(section, option, vars=vars)
  File "/usr/lib/python3.10/configparser.py", line 820, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 810, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 805, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: ''

Line 33:
settings = ReadSettings()
    categories = [settings.SAB['sb'], settings.SAB['sonarr'], settings.SAB['radarr'], settings.SAB['sr'], settings.SAB['bypass']]

Within SAB, I have categories as tv and movies, should the above line set to those?
Thanks

Forgot to add, the two DL's I tried are not importing to sonarr, stuck in sab, so something not completing

**Comment by mdhiggins** [comment]
Python's configparser expects certain datatypes to be present

`self.Plex['port'] = config.getint(section, "port")`

`ValueError: invalid literal for int() with base 10: ''`

You must have deleted or put some non integer value in the plex port setting

The plex settings aren't acted on unless `refresh=true` so you don't need to go blanking out the default values
